fix(DTFS2-7608): syntax fix

diff --git a/.github/modules/rerun/action.yml b/.github/modules/rerun/action.yml
--- a/.github/modules/rerun/action.yml
+++ b/.github/modules/rerun/action.yml
@@ -30,18 +30,29 @@ runs:
         # Set the arguments
         maximum=${{ inputs.retries }}
         env="${{ inputs.env }}"
+        passed=0
 
         # Change to working directory
         cd ${{ inputs.working-directory }} || exit 1
 
         # Retry loop execution
         for((run=0; run<=maximum; run++));do
+        echo "Run #$run/$maximum"
           eval "$env"
           eval "${{ inputs.command }}"
 
           # Exit with success
           if [ $? -eq 0 ]; then
-            exit 0
+            echo "Passed on run#$run"
+            passed=1
+            break
           fi
         done
+
+
+          # Exit with success
+          if [ $passed -eq 0 ]; then
+            echo "Step failed on run#$run"
+            exit 1
+          fi
       shell: bash
