fix(DTFS2-7608): fixed bash syntax errors

diff --git a/.github/modules/rerun/action.yml b/.github/modules/rerun/action.yml
--- a/.github/modules/rerun/action.yml
+++ b/.github/modules/rerun/action.yml
@@ -38,16 +38,19 @@ runs:
         # Specify environment variables
         eval "$env"
 
+        # Exit immediately upon failure
+        set -e
+
         # Retry loop execution
         while [ $run -le $maximum ]; do
           bash -c "${{ inputs.command }}"
 
           if [ $? -eq 0 ]; then
-            exit 0;
+            exit 0
           fi
           
-          run = $((run + 1))
+          run=$((run + 1))
         done
 
-        exit 1;
+        exit 1
       shell: bash
