feat(DTFS2-16188): deploy resources

diff --git a/.github/workflows/bicep_infrastructure.yml b/.github/workflows/bicep_infrastructure.yml
--- a/.github/workflows/bicep_infrastructure.yml
+++ b/.github/workflows/bicep_infrastructure.yml
@@ -93,7 +93,12 @@ jobs:
         uses: azure/login@v2
         with:
           creds: ${{ secrets.AZURE_DEV_CREDENTIALS }} 
-      
+          
+      - name: Check working directory and files
+        run: |
+          pwd
+          ls -R dtfs2/infrastructure/resource_group_level || echo "❌ Directory not found"
+
       - name: Replace GitHub variables into parameters.json 
         run: | 
           # Replace GitHub variables into parameters.json 
